version: "3.7"
services:

## prometheus
  prometheus:
    image: quay.io/prometheus/prometheus:v3.6.0
    container_name: prometheus
    volumes:
     - ${PWD}/compose/data/prometheus/etc:/etc/prometheus/
     - ${PWD}/compose/data/prometheus/data:/prometheus/
    command: '--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.enable-admin-api'
    ports:
     - 9090:9090
    networks:
     - grafana_net
     
## grafana
  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    user: 0:0
    ports:
     - 3000:3000
    volumes:
     - ${PWD}/compose/data/grafana/etc:/etc/grafana/
     - ${PWD}/compose/data/grafana/etc/provisioning/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
     - ${PWD}/compose/data/grafana/data:/var/lib/grafana
    networks:
     - grafana_net
    depends_on: 
      - prometheus

networks:
  grafana_net:
    driver: bridge