{
 "title": "05-01-Grafana-Time-Series-template",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "05-01-01-Time-series-Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance,mode) (rate(node_cpu_seconds_total{}[5m])) * 100)",
     "legendFormat": "{{instance-mode}}"
    }
   ]
  },
  {
   "title": "05-01-02-Time-series-Stat",
   "type": "stat",
   "description": "load per CPU core” (percent)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "100 * node_load5\r\n/ on(instance)\r\ncount(count(node_cpu_seconds_total{}) by (instance, cpu)) by (instance)",
     "legendFormat": "{{instance}}-{{mode}}"
    }
   ]
  },
  {
   "title": "05-01-03-Time-series-Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance,mode) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "05-01-04-Time-series-Bar-gauge",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance,mode) (rate(node_cpu_seconds_total{}[5m])) * 100)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "05-01-05-Time-series-Bar-chart",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance,mode) (rate(node_cpu_seconds_total{}[5m])) * 100)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "05-01-06-Time-series-Pie-chart-or-Donut chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance,mode) (rate(node_cpu_seconds_total{}[5m])) * 100)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "05-01-07-Time-series-Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "rate(app_event_total{}[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "05-01-08-Time-series-Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "app_event_total{}", "legendFormat": "{{name}}" }
   ]
  }
 ]
}